//
// Created by Templier Bourda Tancrède on 27/01/2026.
//

#ifndef ROBOTTRIANGULARISE_MAINFORCOMMUNICATION_H
#define ROBOTTRIANGULARISE_MAINFORCOMMUNICATION_H

""


#endif //ROBOTTRIANGULARISE_MAINFORCOMMUNICATION_H